"""
Pascal’s triangle is a nice shape formed by the arrangement of numbers in a
triangular array, constructed by summing adjacent elements in preceding rows.
Each number is generated by taking the sum of the two numbers above it.
The outside edges of this triangle are always 1.

The expected triangle is shown below:

>>> pascal_triangle(6)
[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]

"""